name: MP_Windows

on: 
  push:
    paths:
      - '.github/**'
      - 'mp/src/**'
  pull_request:
   paths:
      - 'mp/src/**'

jobs:
  build:
    runs-on:
      windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure dependencies
        uses: ilammy/msvc-dev-cmd@v1
        
      - name: Create project
        run: cd mp/src;devtools/bin/vpc.exe /custom /2013 +gamedlls /mksln tehcooler.sln

      - name: Build project
        run: cd mp/src;devenv tehcooler.sln /Build Release

      - name: Pack
        shell: bash
        run: tar cJfv Windows.tar.xz mp/game/mod_custom/bin

      - name: Upload product
        uses: actions/upload-artifact@v4.4.3
        with:
          name: tehcooler_dlls
          path: Windows.tar.xz
