name: MP_Windows

on: 
  push:
    paths:
      - '.github/**'
      - 'mp/src/**'
  pull_request:
   paths:
      - 'mp/src/**'

jobs:
  build:
    runs-on:
      windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure dependencies
        uses: ilammy/msvc-dev-cmd@v1
        
      - name: Create project
        run: cd mp/src;devtools/bin/vpc.exe /custom /2022 +game /mksln custom.sln

      - name: Build project
        run: cd mp/src;devenv custom.sln /Build Release
        
      - name: Copy DLLs to game repo
        uses: nkoppel/push-files-to-another-repository@v1.1.2
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-files: 'mp\game\mod_custom\bin'
          destination-username: 'Almixo'
          destination-repository: 'Spectruminary-Game'
          destination-directory: 'bin'
          commit-email: '111447259+Almixo@users.noreply.github.com'
