name: MP_Windows

on: 
  push:
    paths:
      - '.github/**'
      - 'mp/src/**'
  pull_request:
   paths:
      - 'mp/src/**'

jobs:
  build:
    runs-on:
      windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure dependencies
        uses: ilammy/msvc-dev-cmd@v1
        
      - name: Create project
        run: cd mp/src;devtools/bin/vpc.exe /custom /2022 +game /mksln custom.sln

      - name: Build project
        run: cd mp/src;devenv custom.sln /Build Release
