name: SP_Windows

on: 
  push:
    paths:
      - '.github/**'
      - 'sp/src/**'
  pull_request:
   paths:
      - 'sp/src/**'

jobs:
  build:
    runs-on:
      windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure dependencies
        uses: ilammy/msvc-dev-cmd@v1
        
      - name: Create project
        run: cd sp/src;devtools/bin/vpc.exe /hl1 /2019 +game /mksln hl1-ce.sln

      - name: Build project
        run: cd sp/src;devenv hl1-ce.sln /Build Release

      - name: Pack
        shell: bash
        run: tar cJfv Windows.tar.xz sp/game/mod_hl1/bin

      - name: Upload product
        uses: actions/upload-artifact@v2
        with:
          name: sp_hl1
          path: Windows.tar.xz
